### ISSUE TITLE
请问对于gaokao-bench的评估，你们的prompt是怎么构造的？

### ISSUE THREAD

**Issue by liu904-61** [xverse-ai/XVERSE-65B#5]
使用的是gaokao-bench 自身的prompt文件吗？
如果自定义的话，可以给个case吗？

**Comment by moiSusu** [comment]
> 使用的是gaokao-bench 自身的prompt文件吗？ 如果自定义的话，可以给个case吗？

使用的是自定义的prompt，比如：

**Comment by moiSusu** [comment]
> 使用的是gaokao-bench 自身的prompt文件吗？ 如果自定义的话，可以给个case吗？

使用的是自己定义的prompt，比如

**Comment by moiSusu** [comment]
> 使用的是gaokao-bench 自身的prompt文件吗？ 如果自定义的话，可以给个case吗？

使用的是自定义的prompt，一个case：

以下是中国高考英语试卷中的题目，请从所给选项中选择一个正确答案填入题目中的空格或者横线部分。

10. Mary , I       John  of his promise  to help you.
选项：
A. told
B. reminded
C. warned
D. advised
答案：B

25. I got to the office  earlier  that day,        the 7:30 train from  Paddington .
选项：
A. caughl
B. to have  caught
C. to catch
D. having  caught
答案：D

25. Tony  can hardly  boil an egg, still      cook  dinner.
选项：
A. less
B. little
C. much
D. more
答案：A

28. When  you are home , give a call to let me know  you        safely .
选项：
A. are arriving
B. have  arrived
C. had arrived
D. will arrive
答案：B

21. --- I’m sorry  I made  a mistake!     ---      . Nobody  is perfect.
选项：
A. Take  your time
B. You’re right
C. Whatever  you say
D. Take  it easy
答案：D

21. --- Have  you finished  reading  Jane  Eyre ? 
--- No, I        my homework  all day yesterday .
选项：
A. was doing
B. would  do
C. had done
D. do
答案：

**Comment by moiSusu** [comment]
> 使用的是gaokao-bench 自身的prompt文件吗？ 如果自定义的话，可以给个case吗？

使用的是自定义的prompt：
以下是中国高考英语试卷中的题目，请从所给选项中选择一个正确答案填入题目中的空格或者横线部分。

10. Mary , I       John  of his promise  to help you.
选项：
A. told
B. reminded
C. warned
D. advised
答案：B

25. I got to the office  earlier  that day,        the 7:30 train from  Paddington .
选项：
A. caughl
B. to have  caught
C. to catch
D. having  caught
答案：D

25. Tony  can hardly  boil an egg, still      cook  dinner.
选项：
A. less
B. little
C. much
D. more
答案：A

28. When  you are home , give a call to let me know  you        safely .
选项：
A. are arriving
B. have  arrived
C. had arrived
D. will arrive
答案：B

21. --- I’m sorry  I made  a mistake!     ---      . Nobody  is perfect.
选项：
A. Take  your time
B. You’re right
C. Whatever  you say
D. Take  it easy
答案：D

21. --- Have  you finished  reading  Jane  Eyre ? 
--- No, I        my homework  all day yesterday .
选项：
A. was doing
B. would  do
C. had done
D. do
答案：

**Comment by liu904-61** [comment]
好的，非常感谢你的回复。

**Comment by liu904-61** [comment]
你们在高考测试集里，对于高考英语完型填空和语文阅读理解做了评测吗？这两个都比较长，好像不适合做5shot，甚至1shot都不一定可以做到。
